### ISSUE TITLE
Question. Values from durable object

### ISSUE THREAD

**Issue by nikitapilgrim** [kwhitley/itty-durable#40]
I can't access the values from the durable object. 
They become visible only in the response
  
  You have such an example
  .get('/', ({ Counter }) => Counter.get('test').toJSON())
  
  I have something like this
 `  .get('/', async ({ Counter }) => {
         const state =  await Counter.get('test').toJSON());
         console.log(JSON.stringify(state), state);
         return json(state);
     }
`

the response in the cloudflare worker dashboard.
```

 "message": [
        "{}",
        "[object Object]"
      ],
      
```
      
but the response in the browser is fine, I can see all the values of the object.

**Comment by kwhitley** [comment]
So if you don’t use the parse flag (autoParse?) on the withDurables middleware, the response back from a DO method (e.g. toJSON) will be a Response, not the raw data. So you wouldn’t want to stringify it. Your final json method is ignoring it because it’s already a valid Response, so it still return just fine in the end.~KevinOn Jul 23, 2023, at 00:46, Nikita Pilgrim ***@***.***> wrote:﻿
I can't access the values from the durable object.
They become visible only in the response
You have such an example
.get('/', ({ Counter }) => Counter.get('test').toJSON())
I have something like this
 .get('/', async ({ Counter }) => { const state =  await Counter.get('test').toJSON()); console.log(JSON.stringify(state), state); return json(state); }
the response in the cloudflare worker dashboard.

 "message": [
        "{}",
        "[object Object]"
      ],
      

but the response in the browser is fine, I can see all the values of the object.
